param(
    [Parameter(Mandatory = $true)]
    [string]$SourceDirectoryPath,
    [Parameter(Mandatory = $true)]
    [string]$BundleVersion,
    [Parameter(Mandatory = $true)]
    [string]$SourceRevision,
    [string]$ObjDirName = 'obj-claw-links-windows-esr',
    [string]$BrandingPath = 'browser/branding/unofficial',
    [string]$Platform = 'windows-x64',
    [string]$Architecture = 'x64',
    [string]$ReleaseChannel = 'staging',
    [string]$DisplayName = 'Claw Browser',
    [string]$EntryExecutableRelativePath = 'firefox.exe',
    [ValidateSet('warning', 'strict', 'off')]
    [string]$RuntimeValidationMode = 'strict',
    [string]$BuildArtifactsRoot = '',
    [switch]$NoRedist,
    [switch]$NoSccache
)

$ErrorActionPreference = 'Stop'

function ConvertTo-MsysPath {
    param(
        [Parameter(Mandatory = $true)]
        [string]$WindowsPath
    )

    $fullPath = [System.IO.Path]::GetFullPath($WindowsPath)
    $normalized = $fullPath -replace '\\', '/'

    if ($normalized -match '^([A-Za-z]):/(.*)$')
    {
        return "/$($matches[1].ToLowerInvariant())/$($matches[2])"
    }

    throw "Unable to convert Windows path '$WindowsPath' to an MSYS path."
}

$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent (Split-Path -Parent $scriptRoot)

if (!(Test-Path -LiteralPath $SourceDirectoryPath))
{
    throw @"
Firefox source checkout not found at '$SourceDirectoryPath'.

To create the expected ESR checkout on Windows:

  New-Item -ItemType Directory -Force C:\mozilla-source | Out-Null
  hg clone https://hg.mozilla.org/releases/mozilla-esr128 C:\mozilla-source\firefox

Then rerun:

  .\packaging\windows\Start-WindowsFirefoxEsrBuild.ps1 -SourceDirectoryPath C:\mozilla-source\firefox -BundleVersion $BundleVersion -SourceRevision $SourceRevision

If 'hg' is not installed yet, first follow Mozilla's Windows build setup guidance and MozillaBuild/bootstrap steps in docs/firefox-build.md.
"@
}

$resolvedSourceDirectory = (Resolve-Path -LiteralPath $SourceDirectoryPath).Path
$machPath = Join-Path $resolvedSourceDirectory 'mach'
$objDirWindows = Join-Path $resolvedSourceDirectory $ObjDirName
$packagedBrowserDirectory = Join-Path $objDirWindows 'dist\firefox'

if ([string]::IsNullOrWhiteSpace($BuildArtifactsRoot))
{
    $BuildArtifactsRoot = Join-Path $repoRoot 'artifacts\build\windows'
}

$buildArtifactsRootFullPath = [System.IO.Path]::GetFullPath($BuildArtifactsRoot)
$mozconfigPath = Join-Path $buildArtifactsRootFullPath 'windows-esr-build.mozconfig'
$helperScriptPath = Join-Path $buildArtifactsRootFullPath 'run-firefox-esr-build.sh'
$archiveScriptPath = Join-Path $repoRoot 'packaging\windows\New-WindowsBrowserArchive.ps1'

if (!(Test-Path -LiteralPath $machPath))
{
    throw "Expected a Firefox source checkout with a 'mach' entry point at '$machPath'."
}

New-Item -ItemType Directory -Force -Path $buildArtifactsRootFullPath | Out-Null

$mozconfigLines = @(
    '# Generated by packaging/windows/Start-WindowsFirefoxEsrBuild.ps1',
    '# Mozilla docs recommend building from the MozillaBuild shell and using mach build/package on Windows.',
    "mk_add_options MOZ_OBJDIR=@TOPSRCDIR/$ObjDirName",
    'ac_add_options --enable-application=browser',
    "ac_add_options --with-branding=$BrandingPath"
)

if (-not $NoRedist)
{
    $mozconfigLines += 'ac_add_options --with-redist'
}

if (-not $NoSccache)
{
    $mozconfigLines += 'ac_add_options --with-ccache=sccache'
}

$mozconfigLines += ''
$mozconfigLines += '# Keep launcher-owned policies and profile data outside the Firefox build tree.'

Set-Content -Path $mozconfigPath -Value (($mozconfigLines -join [Environment]::NewLine) + [Environment]::NewLine) -Encoding ascii

$sourceDirectoryMsys = ConvertTo-MsysPath -WindowsPath $resolvedSourceDirectory
$mozconfigMsys = ConvertTo-MsysPath -WindowsPath $mozconfigPath
$packagedBrowserDirectoryMsys = ConvertTo-MsysPath -WindowsPath $packagedBrowserDirectory
$helperLines = @(
    '#!/usr/bin/env bash',
    'set -euo pipefail',
    '',
    '# Generated by packaging/windows/Start-WindowsFirefoxEsrBuild.ps1',
    "cd '$sourceDirectoryMsys'",
    "export MOZCONFIG='$mozconfigMsys'",
    '',
    './mach build',
    './mach package',
    '',
    "if [ ! -d '$packagedBrowserDirectoryMsys' ]; then",
    "  echo 'Expected packaged browser directory at $packagedBrowserDirectory after mach package.' >&2",
    '  exit 1',
    'fi',
    '',
    "powershell.exe -NoProfile -ExecutionPolicy Bypass -File '$archiveScriptPath' -SourceDirectoryPath '$packagedBrowserDirectory' -BundleVersion '$BundleVersion' -SourceRevision '$SourceRevision' -Platform '$Platform' -Architecture '$Architecture' -UpstreamProductLine 'esr' -ReleaseChannel '$ReleaseChannel' -DisplayName '$DisplayName' -EntryExecutableRelativePath '$EntryExecutableRelativePath' -RuntimeValidationMode '$RuntimeValidationMode'"
)

Set-Content -Path $helperScriptPath -Value (($helperLines -join "`n") + "`n") -Encoding ascii

Write-Host 'Windows Firefox ESR build helper prepared.'
Write-Host "Source checkout: $resolvedSourceDirectory"
Write-Host "Generated mozconfig: $mozconfigPath"
Write-Host "Generated helper script: $helperScriptPath"
Write-Host
Write-Host 'Run the generated helper from the MozillaBuild shell:'
Write-Host '  1. Start C:\mozilla-build\start-shell.bat'
Write-Host "  2. Run $((ConvertTo-MsysPath -WindowsPath $helperScriptPath))"
Write-Host
Write-Host 'The helper will run:'
Write-Host '  - ./mach build'
Write-Host '  - ./mach package'
Write-Host '  - packaging/windows/New-WindowsBrowserArchive.ps1'
Write-Host
Write-Host "Expected packaged browser directory: $packagedBrowserDirectory"
